version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: always
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    restart: always
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    restart: always
