version: '3.8'

services:
#-----------NGINX----------------
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/wordpress:/var/www/wordpress
    networks:
      - wp_network
    depends_on:
      - wordpress
    restart: always
    env_file:
      - .env 
#-----------WORDPRESS----------------
  wordpress:
    build:
      context: ./requirements/wordpress
    volumes:
      - ./requirements/wordpress:/var/www/html
    networks:
      - wp_network
    depends_on:
      - mariadb
    restart: always
    env_file:
      - ./.env  
#-----------MARIADB----------------
  mariadb:
    build:
      context: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wp_network
    restart: always
    env_file:
      - ./.env 
#-----------NETWORKS----------------
networks:
  wp_network:
    driver: bridge
#-----------VOLUMES----------------
volumes:
  mariadb_data:
