services:
  
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:42
    container_name: mariadb
    env_file:
      - ./.env
    volumes:
      - Mdb:/var/lib/mysql
    restart: on-failure
    networks:
      - net

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:42
    container_name: wordpress
    env_file:
      - ./.env
    volumes:
      - Wp:/var/www/html
    depends_on:
      - mariadb
    restart: on-failure
    networks:
      - net

  ngnix:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx:42
    container_name: ngnix
    ports:
      - 443:443
    env_file:
      - ./.env
    volumes:
      - Wp:/var/www/html
    depends_on:
      - wordpress
    restart: on-failure
    networks:
      - net

networks:
  net:
    name : net

volumes:
  Wp:
    # driver_opts:
    #   o: bind
    #   type: none
    #   device: /home/abberkac/data/wp-data
  Mdb:
    # driver_opts:
    #   o: bind
    #   type: none
    #   device: /home/abberkac/data/db-data
